baseURL = 'https://dalehartleyemery.com/'
languageCode = 'en-us'
title = 'Dale Hartley Emery'
copyright = '© 2013–2023 Dale Hartley Emery'

theme = 'Dale'

[taxonomies]
tag = 'tags'

[markup.goldmark.renderer]
unsafe = true
